service: shopco-basket-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: us-east-2
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-location-${opt:stage, self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:*
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  exclude:
    - env/**
    - node_modules/**
    - secrets.yml
    - .gitignore

functions:
  create:
    handler: basket/create.create
    events:
      - http:
          path: basket
          method: post
          cors: true
  update:
    handler: basket/update.update
    events:
      - http:
          path: basket/{id}
          method: put
          cors: true
  delete:
    handler: basket/delete.delete
    events:
      - http:
          path: basket/{id}
          method: delete
          cors: true
  list:
    handler: basket/list.list
    events:
      - http:
          path: basket/{id}
          method: get
          cors: true
  get:
    handler: basket/get.get
    events:
      - http:
          path: basket/{id}/{product_id}
          method: get
          cors: true

resources:
  Resources:
    BasketDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: customer_id
            AttributeType: S
          -
            AttributeName: product_id
            AttributeType: S
        KeySchema:
          - 
            AttributeName: customer_id
            KeyType: HASH
          -
            AttributeName: product_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}
  pythonRequirements:
    dockerizePip: false